test_format = 1.0

[default]

    args.redirect_type = "redirect"
    args.target = "http://127.0.0.1"

    test_upgrade_from.09cf1c6b.name = "v1 era"
    test_upgrade_from.09cf1c6b.args.domain = "domain.tld"
    test_upgrade_from.09cf1c6b.args.redirect_type = "visible_302"
    test_upgrade_from.09cf1c6b.args.redirect_path = "http://127.0.0.1"


[reverseproxy]

    args.redirect_type = "reverseproxy"
    args.target = "http://127.0.0.1"

    exclude = ["install.private", "install.multi", "backup_restore"]

    test_upgrade_from.09cf1c6b.name = "v1 era"
    test_upgrade_from.09cf1c6b.args.domain = "domain.tld"
    test_upgrade_from.09cf1c6b.args.redirect_type = "proxy_public"
    test_upgrade_from.09cf1c6b.args.redirect_path = "http://127.0.0.1"
