#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.redirect_type = "redirect"
    args.target = "http://127.0.0.1"

    [default.test_upgrade_from.09cf1c6b]
    name = "v1 era"
    args.domain = "domain.tld"
    args.redirect_type = "visible_302"
    args.redirect_path = "http://127.0.0.1"


[reverseproxy]

    args.redirect_type = "reverseproxy"
    args.target = "http://127.0.0.1"

    exclude = ["install.private", "install.multi", "backup_restore"]

    [reverseproxy.test_upgrade_from.09cf1c6b]
    name = "v1 era"
    args.domain = "domain.tld"
    args.redirect_type = "proxy"
    args.redirect_path = "http://127.0.0.1"
