#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

# Copy the conf files
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
